/**
 * 
 */
package io.crs.hsys.shared.exception;

/**
 * @author robi
 *
 */
public enum ExceptionSubType {
	APPUSER_EMAIL_ALREADY_EXISTS, APPUSER_CODE_ALREADY_EXISTS, USERGROUP_NAME_ALREADY_EXISTS,
	PROFILEGROUP_CODE_ALREADY_EXISTS, MARKETGROUP_CODE_ALREADY_EXISTS, ROOMTYPECODE_CODE_ALREADY_EXISTS,
	ROOMCODE_CODE_ALREADY_EXISTS, TASKGROUP_CODE_ALREADY_EXISTS, TASKTODO_DESCRIPTION_ALREADY_EXISTS,
	TASKTYPE_CODE_ALREADY_EXISTS, TASKGROUP_ID_USED_BY_TASKTODO, TASKGROUP_ID_USED_BY_TASKTYPE;

}
